id: group_content
label: 'Group content'
ui_limit: ''
properties:
  block: 'views_block:group_nodes-group_nodes_group_content'
  use_block_title: false
  config:
    id: 'views_block:group_nodes-group_nodes_group_content'
    label: ''
    provider: views
    label_display: visible
    views_label: ''
    items_per_page: none
type: block
type_label: 'Block field'
entities:
  group: group
